[project]
name = "linkedinjobpostings"
version = "0.1.0"
description = "Scrap job posting from LinkedIn guest job postings page and store them in csv format"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.41",
]
